# Generated by Django 4.0.6 on 2023-10-28 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('match', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.tag'),
        ),
        migrations.AddField(
            model_name='match',
            name='task1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task1_matches', to='task.task'),
        ),
        migrations.AddField(
            model_name='match',
            name='task2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task2_matches', to='task.task'),
        ),
        migrations.AddField(
            model_name='match',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_matches', to='account.user'),
        ),
        migrations.AddField(
            model_name='match',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_matches', to='account.user'),
        ),
    ]
