# Generated by Django 4.2.6 on 2023-10-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MakeTask", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="duration",
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name="task",
            name="tags",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.CharField(
                choices=[
                    ("programming", "プログラミング"),
                    ("exam", "受験"),
                    ("assignment", "課題"),
                ],
                default="programming",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
