# Generated by Django 4.2.6 on 2023-10-29 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("MakeTask", "0003_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="matched_users",
            field=models.ManyToManyField(
                blank=True, related_name="matched_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
