# Generated by Django 4.2.6 on 2023-10-29 01:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MakeTask", "0004_task_matched_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="matched_users",
        ),
    ]
